Add notif download
exoplatform/exo-android pull request #111
Opened 2022-04-05 08:58 UTC by wbenabdessalem

Use native system when i download a document.

Given I'm a user in the platform using the mobile app

When i donwload a document

Then the native system should be applied to download it and display the progress of this download.

2022-04-05 15:58 UTC, rdenarie requested changes

2022-04-05 15:58 UTC, rdenarie commented on app/src/main/java/org/exoplatform/tool/JavaScriptInterface.java
> +package org.exoplatform.tool;
Can you add header

2022-04-05 16:07 UTC, wbenabdessalem commented on app/src/main/java/org/exoplatform/tool/JavaScriptInterface.java
> +package org.exoplatform.tool;
Done

2022-04-05 16:11 UTC, rdenarie requested changes

2022-04-05 16:11 UTC, rdenarie commented on app/src/main/java/org/exoplatform/tool/JavaScriptInterface.java
> + * Copyright (C) 2003-2019 eXo Platform SAS.
```suggestion
 * Copyright (C) 2022 eXo Platform SAS.
```

2022-04-05 16:11 UTC, rdenarie requested changes
the copyright is not the good one.
You need to take the AGPL as you are on exoplatform organization

2022-04-06 09:30 UTC, wbenabdessalem commented
Can you check again please ?

2022-04-06 11:30 UTC, rdenarie requested changes

2022-04-06 11:30 UTC, rdenarie commented on app/src/main/AndroidManifest.xml
> +
```suggestion
```

2022-04-06 11:30 UTC, rdenarie commented on app/src/main/AndroidManifest.xml
> +
```suggestion
```

2022-04-06 11:30 UTC, rdenarie commented on app/src/main/AndroidManifest.xml
> +
```suggestion
```

2022-04-06 12:14 UTC, rdenarie requested changes

2022-04-06 12:14 UTC, rdenarie commented on app/src/main/AndroidManifest.xml
> +
```suggestion
```

2022-04-06 12:14 UTC, rdenarie commented on app/src/main/AndroidManifest.xml
> +
```suggestion
```

2022-04-06 12:14 UTC, rdenarie approved these changes

2022-04-06 12:31 UTC, merged