Task-59006: when scanning a wrong QR code, an error message display
exoplatform/exo-android pull request #139
Opened 2022-07-19 13:32 UTC by wbenabdessalem

Fix: Add check about the scanned qr code

2022-07-19 14:18 UTC, ahamdi requested changes

2022-07-19 14:18 UTC, ahamdi commented on app/src/main/java/org/exoplatform/activity/ScannerActivity.java
> +                    e.printStackTrace();
We should not print exceptions, please use Logger instead.

2022-07-19 14:18 UTC, ahamdi commented on app/src/main/java/org/exoplatform/activity/ScannerActivity.java
> +                detectedURL.setText("Not valid URL");
```suggestion
                detectedURL.setText("Invalid URL");

```

2022-07-19 14:18 UTC, ahamdi commented on app/src/main/java/org/exoplatform/activity/ScannerActivity.java
> +                detectedURL.setText("Not valid URL");
We need to internationalie this text.

2022-07-19 14:47 UTC, wbenabdessalem commented on app/src/main/java/org/exoplatform/activity/ScannerActivity.java
> +                detectedURL.setText("Not valid URL");
Done

2022-07-20 11:39 UTC, ahamdi commented on app/src/main/res/values/strings.xml
> +    "Invalid URL"
This is an invalid XML structure, would it work for strings internationalization ?

2022-07-20 14:35 UTC, wbenabdessalem commented on app/src/main/res/values/strings.xml
> +    "Invalid URL"
comment to ignore and should be deleted

2022-07-20 15:28 UTC, ahamdi approved these changes

2022-07-21 07:50 UTC, merged