FT Android: Reach the level of iOS App
exoplatform/exo-android pull request #30
Opened 2021-09-16 11:07 UTC by wbenabdessalem

FT Android: Reach the level of iOS App

2021-09-16 11:42 UTC, ahamdi requested changes

2021-09-16 11:42 UTC, ahamdi commented on app/src/main/java/org/exoplatform/service/push/PushNotificationsService.java
> +      System.out.println("urlKey ===> " + urlKey);
To remove

2021-09-16 11:42 UTC, ahamdi commented on app/src/main/java/org/exoplatform/service/push/PushNotificationsService.java
> +      e.printStackTrace();
Use logger 
```suggestion
      Log.e("Malformed URL",e);
```

2021-09-16 13:05 UTC, wbenabdessalem commented on app/src/main/java/org/exoplatform/service/push/PushNotificationsService.java
> +      e.printStackTrace();
Done

2021-09-16 17:37 UTC, ahamdi commented on app/src/main/java/org/exoplatform/service/push/PushNotificationsService.java
> +      System.out.println("rootURL ===> " + rootURL.toString());
to remove

2021-09-16 17:40 UTC, ahamdi requested changes

2021-09-16 17:40 UTC, ahamdi commented on app/src/main/java/org/exoplatform/service/push/PushNotificationsService.java
> +      count = count + 1;
```suggestion
      count = shared.getInt(urlKey, 0) + 1;
```

2021-09-16 17:40 UTC, ahamdi commented on app/src/main/java/org/exoplatform/service/push/PushNotificationsService.java
> +      String urlKey = urlProtocol + "://" + urlDomain;
Get the URL with one instruction

2021-09-23 11:22 UTC, ahamdi commented on app/build.gradle
> +        versionName "5.1.7"
```suggestion
        versionCode 01
        versionName "6.2.0"
```

2021-09-23 11:23 UTC, ahamdi commented on app/build.gradle
> -        }
To restore

2021-09-23 11:23 UTC, ahamdi commented on app/build.gradle
> -            if (names.contains("dev") || names.contains("beta") || names.contains("store")) {
To restore

2021-09-24 13:43 UTC, closed without merging