47906 : Display pop-up by clicking on delete icone on instance page
exoplatform/exo-android pull request #41
Opened 2021-10-29 22:09 UTC by wbenabdessalem

Given i am PLF mobile user

When i am deconnected or my session time out

And i click on delete icone

Then i want to have a pop-up "Delete confirmation"

--------------------------------------------------------------------

Given the previous step

When I clic on button 'delete'

Then card are not displayed any more

--------------------------------------------------------------------

Given the fist step

When I clic on button "Cancel"

Then the pop-up is closed 

Link to design : 

https://projects.invisionapp.com/share/H8113BGYJAGT#/screens/454431114

2021-10-30 09:46 UTC, ahamdi requested changes

2021-10-30 09:46 UTC, ahamdi commented on app/src/main/java/org/exoplatform/activity/ConnectToExoListActivity.java
Unneeded import

2021-11-01 08:39 UTC, wbenabdessalem commented on app/src/main/java/org/exoplatform/activity/ConnectToExoListActivity.java
Done

2021-11-01 08:54 UTC, ahamdi approved these changes

2021-11-01 09:03 UTC, merged